In [1]:
import numpy as np
import pandas as pd

In [2]:
def calc_avg_median_min_max_emb(stats): #avg, med, min, max
    # a function to create a vector of n average embeddings for each
    # tinder profile
    # get the embeddings per profile
    labels = np.load('labels.npy', allow_pickle=True)
    # label_strings = np.load('label_strings.npy', allow_pickle=True)
    embeddings = np.load('embeddings.npy', allow_pickle=True)
    image_list = np.load('image_list.npy', allow_pickle=True)

    # determine the n dimension of embeddings
    n_emb = embeddings.shape[1]

    # find the maximum number of images in a profile
    split_image_list = []
    profile_list = []
    for i in image_list:
        split_image_list.append(i.split('.')[1])
        # split_image_list.append(i.replace('/', '.').split('.'))
        profile_list.append(i.split('.')[0])

    # convert profile list to pandas index
    pl = pd.Index(profile_list)
    pl_unique = pl.value_counts()

    # get the summar statics of pl
    pl_describe = pl_unique.describe()
    print('Summary statistics of profiles with at least one detectable face')
    print(pl_describe)
    number_of_profiles = int(pl_describe[0])
    # number_of_images = int(pl_describe[-1])

    # convert the embeddings to a data frame
    eb = pd.DataFrame(embeddings, index=pl)
    dislike = pd.Series(labels, index=pl)
    # if dislike == 1 it means I disliked the person!

    # create a blank numpy array for embeddings
    new_embeddings = np.zeros((number_of_profiles, n_emb))
    new_labels = np.zeros(number_of_profiles)
    for i, j in enumerate(pl_unique.index):
        temp = eb.loc[j]

        # if a profile has more than one face it will be a DataFrame
        # else the profile will be a Series
        if isinstance(temp, pd.DataFrame):
            # get the average of each column
            if stats == 'avg':
                temp_embeddings = np.mean(temp.values, axis=0)
            elif stats == 'med':
                temp_embeddings = np.median(temp.values, axis=0)
            elif stats == 'min':
                temp_embeddings = np.min(temp.values, axis=0)
            else:
                temp_embeddings = np.max(temp.values, axis=0)
        else:
            temp_embeddings = temp.values

        # save the new embeddings
        new_embeddings[i] = temp_embeddings

        # Save the profile label, 1 for dislike, 0 for like
        new_labels[i] = dislike[j].max()

    # save the files
    np.save(f'embeddings_{stats}_profile.npy', new_embeddings)
    np.save(f'labels_{stats}_profile.npy', new_labels)
    return new_embeddings, new_labels

In [7]:
def calc_avg_emb():
    # a function to create a vector of n average embeddings for each
    # tinder profile
    # get the embeddings per profile
    labels = np.load('labels.npy', allow_pickle=True)
    # label_strings = np.load('label_strings.npy', allow_pickle=True)
    embeddings = np.load('embeddings.npy', allow_pickle=True)
    image_list = np.load('image_list.npy', allow_pickle=True)

    # determine the n dimension of embeddings
    n_emb = embeddings.shape[1]

    # find the maximum number of images in a profile
    split_image_list = []
    profile_list = []
    for i in image_list:
        split_image_list.append(i.split('.')[1])
        # split_image_list.append(i.replace('/', '.').split('.'))
        profile_list.append(i.split('.')[0])

    # convert profile list to pandas index
    pl = pd.Index(profile_list)
    pl_unique = pl.value_counts()

    # get the summar statics of pl
    pl_describe = pl_unique.describe()
    print('Summary statistics of profiles with at least one detectable face')
    print(pl_describe)
    number_of_profiles = int(pl_describe[0])
    # number_of_images = int(pl_describe[-1])

    # convert the embeddings to a data frame
    eb = pd.DataFrame(embeddings, index=pl)
    dislike = pd.Series(labels, index=pl)
    # if dislike == 1 it means I disliked the person!

    # create a blank numpy array for embeddings
    new_embeddings = np.zeros((number_of_profiles, n_emb))
    new_labels = np.zeros(number_of_profiles)
    for i, j in enumerate(pl_unique.index):
        temp = eb.loc[j]

        # if a profile has more than one face it will be a DataFrame
        # else the profile will be a Series
        if isinstance(temp, pd.DataFrame):
            # get the average of each column
            temp_embeddings = np.mean(temp.values, axis=0)
        else:
            temp_embeddings = temp.values

        # save the new embeddings
        new_embeddings[i] = temp_embeddings

        # Save the profile label, 1 for dislike, 0 for like
        new_labels[i] = dislike[j].max()

    # save the files
#     np.save('embeddings_avg_profile.npy', new_embeddings)
#     np.save('labels_avg_profile.npy', new_labels)
    return new_embeddings, new_labels


In [8]:
calc_avg_emb()

Summary statistics of profiles with at least one detectable face
count    8132.000000
mean        3.016724
std         1.344842
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max        10.000000
dtype: float64


(array([[-0.08516867, -0.0960011 ,  0.01026064, ..., -0.04686032,
          0.13399079,  0.03843592],
        [-0.05853223, -0.11806548,  0.07782068, ..., -0.05917085,
          0.08974024,  0.03685835],
        [-0.05148027, -0.12753478,  0.04967369, ..., -0.0115897 ,
          0.08626622,  0.06416687],
        ...,
        [-0.03237536, -0.10986029, -0.05273964, ..., -0.04715952,
          0.13395712, -0.00100789],
        [ 0.01070913, -0.12045956,  0.07860527, ..., -0.03334678,
          0.03928874,  0.03627693],
        [-0.14070714, -0.06604623,  0.02883334, ..., -0.03452408,
          0.07793716,  0.08409154]]),
 array([1., 0., 0., ..., 1., 0., 0.]))

In [3]:
calc_avg_median_min_max_emb('avg')

Summary statistics of profiles with at least one detectable face
count    8132.000000
mean        3.016724
std         1.344842
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max        10.000000
dtype: float64


(array([[-0.08516867, -0.0960011 ,  0.01026064, ..., -0.04686032,
          0.13399079,  0.03843592],
        [-0.05853223, -0.11806548,  0.07782068, ..., -0.05917085,
          0.08974024,  0.03685835],
        [-0.05148027, -0.12753478,  0.04967369, ..., -0.0115897 ,
          0.08626622,  0.06416687],
        ...,
        [-0.03237536, -0.10986029, -0.05273964, ..., -0.04715952,
          0.13395712, -0.00100789],
        [ 0.01070913, -0.12045956,  0.07860527, ..., -0.03334678,
          0.03928874,  0.03627693],
        [-0.14070714, -0.06604623,  0.02883334, ..., -0.03452408,
          0.07793716,  0.08409154]]),
 array([1., 0., 0., ..., 1., 0., 0.]))

In [4]:
calc_avg_median_min_max_emb('med')

Summary statistics of profiles with at least one detectable face
count    8132.000000
mean        3.016724
std         1.344842
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max        10.000000
dtype: float64


(array([[-0.07519082, -0.1175426 ,  0.00910136, ..., -0.04927163,
          0.16132113,  0.02999016],
        [-0.04950605, -0.12248475,  0.10829028, ..., -0.03049106,
          0.10351217,  0.02096421],
        [-0.04570645, -0.14027619,  0.05136904, ..., -0.00679946,
          0.09228221,  0.07515998],
        ...,
        [-0.03237536, -0.10986029, -0.05273964, ..., -0.04715952,
          0.13395712, -0.00100789],
        [ 0.01070913, -0.12045956,  0.07860527, ..., -0.03334678,
          0.03928874,  0.03627693],
        [-0.14070714, -0.06604623,  0.02883334, ..., -0.03452408,
          0.07793716,  0.08409154]]),
 array([1., 0., 0., ..., 1., 0., 0.]))

In [5]:
calc_avg_median_min_max_emb('min')

Summary statistics of profiles with at least one detectable face
count    8132.000000
mean        3.016724
std         1.344842
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max        10.000000
dtype: float64


(array([[-0.16156808, -0.14350794, -0.06150156, ..., -0.10977097,
         -0.0345649 , -0.06470353],
        [-0.13569221, -0.16158943, -0.03907607, ..., -0.15398456,
          0.0323486 , -0.0034484 ],
        [-0.17538778, -0.17867057, -0.04985062, ..., -0.08998743,
         -0.0204369 ,  0.00045404],
        ...,
        [-0.03237536, -0.10986029, -0.05273964, ..., -0.04715952,
          0.13395712, -0.00100789],
        [ 0.01070913, -0.12045956,  0.07860527, ..., -0.03334678,
          0.03928874,  0.03627693],
        [-0.14070714, -0.06604623,  0.02883334, ..., -0.03452408,
          0.07793716,  0.08409154]]),
 array([1., 0., 0., ..., 1., 0., 0.]))

In [9]:
calc_avg_median_min_max_emb('max')

Summary statistics of profiles with at least one detectable face
count    8132.000000
mean        3.016724
std         1.344842
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max        10.000000
dtype: float64


(array([[-3.64640951e-02, -2.99430992e-02,  1.47484884e-01, ...,
          5.72989011e-05,  1.97387069e-01,  1.22476779e-01],
        [-2.04319265e-02, -3.70282605e-02,  1.65327847e-01, ...,
          1.57932658e-02,  1.59090877e-01,  9.91048589e-02],
        [ 1.76914427e-02, -4.80225757e-02,  1.42027855e-01, ...,
          5.95916361e-02,  1.62869394e-01,  9.80631709e-02],
        ...,
        [-3.23753580e-02, -1.09860294e-01, -5.27396388e-02, ...,
         -4.71595190e-02,  1.33957118e-01, -1.00788940e-03],
        [ 1.07091265e-02, -1.20459564e-01,  7.86052719e-02, ...,
         -3.33467834e-02,  3.92887369e-02,  3.62769328e-02],
        [-1.40707135e-01, -6.60462305e-02,  2.88333446e-02, ...,
         -3.45240794e-02,  7.79371560e-02,  8.40915442e-02]]),
 array([1., 0., 0., ..., 1., 0., 0.]))

In [26]:
test = np.load('embeddings_avg_profile.npy')

In [27]:
test

array([[-0.05853227, -0.11806552,  0.07782066, ..., -0.0591709 ,
         0.08974024,  0.0368584 ],
       [-0.08516855, -0.09600114,  0.01026062, ..., -0.04686027,
         0.13399077,  0.03843595],
       [-0.05148031, -0.12753478,  0.04967365, ..., -0.01158976,
         0.08626623,  0.06416689],
       ...,
       [-0.11954832, -0.1497782 ,  0.03150699, ..., -0.04784435,
         0.12846121,  0.05353893],
       [-0.14195977, -0.15345845, -0.02911944, ..., -0.12719192,
         0.08549877,  0.07585432],
       [-0.06043478, -0.07862287, -0.00925292, ..., -0.094113  ,
         0.17042097, -0.00050174]])

In [28]:
np.load('image_list.npy')

array(['TinderOneFaceOnlyFullImage/dislike/538682af0b20d3bd4f4fdfa4.3.jpg',
       'TinderOneFaceOnlyFullImage/dislike/569d83d19d0fe9aa65d64cb7.3.jpg',
       'TinderOneFaceOnlyFullImage/dislike/540b8f9a9cdc8cc8057950ea.2.jpg',
       ...,
       'TinderOneFaceOnlyFullImage/like/557de782f10f41b474601c0e.2.jpg',
       'TinderOneFaceOnlyFullImage/like/57478c476c3e8a230f579f1f.3.jpg',
       'TinderOneFaceOnlyFullImage/like/5797e2c3143e5a9b4e00342d.2.jpg'],
      dtype='<U65')

In [46]:
    image_list = np.load('image_list.npy', allow_pickle=True)

    # determine the n dimension of embeddings
    n_emb = embeddings.shape[1]

    # find the maximum number of images in a profile
    split_image_list = []
    profile_list = []
    for i in image_list:
        split_image_list.append(i.split('.')[1])
        profile_list.append(i.split('.')[0])
    pl = pd.Index(profile_list)
    pl_unique = pl.value_counts()
    print(pl_unique.index.str.split('/').str[-1])

Index(['5391397b56ba04880e01556f', '54d03eaafacf3c333e834320',
       '52f6de9d5c136c8b1100073c', '5722978e2083727d14a8cdf7',
       '57cb7f135ada1cd40f0ed234', '57a7d52be117913218c04d82',
       '57e2154535fbeedd0d6e53b3', '572a66f0c52fda630be545e5',
       '5781ee0a3fd7621d0a663960', '57c7b817e5c527fe1724b4bc',
       ...
       '57d491310360bdb978cd2242', '57c1295ab282c040114d1bcf',
       '57c2520f9b343b4711b81cd4', '576d761c9a3bd981127cea5a',
       '57e75e11bdf2a39b6cc300c4', '57c6491bfb390b83297c87f3',
       '53379031b0f3034b10003f75', '57d2f49d663f5ac6190612aa',
       '5787234345c266f309756624', '53d03d65cd75727b03c0831e'],
      dtype='object', length=8132)


In [47]:
np.save('image_id.npy', pl_unique.index.str.split('/').str[-1])

In [50]:
# len(np.load('image_id.npy',allow_pickle=True))

8132